sonar.projectKey=PlumiaUnlam_plumia-backend
sonar.organization=plumiaunlam

sonar.projectName=PlumIA Backend
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=false

# Source & test paths
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.exclusions=**/*.spec.ts,**/*.e2e-spec.ts,**/node_modules/**,**/dist/**,**/coverage/**,src/main.ts

sonar.coverage.exclusions=src/main.ts,src/app.module.ts,**/*.module.ts,**/*.dto.ts,**/*.entity.ts

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json
